ALTER TABLE notifications
    ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE notifications
    ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMP NULL;

ALTER TABLE notifications
    ADD COLUMN IF NOT EXISTS last_error VARCHAR(500) NULL;
